name: setup-python-action
description: Setup Python and install specified dependencies

inputs:
  python-version:
    description: Version of python to setup
    default: '3.10'
    required: false
  requirements-txt:
    description: Relative path to requirements.txt file. Wildcards can be submitted as well
    default: null
    required: false
  packages:
    description: Space-delimited pip packages to be installed
    default: null
    required: false
  pip-install-args:
    description: Additional arguments to add to the pip install command
    default: null
    required: false
  build-command:
    description: Build command to be executed after installation, if needed
    default: null
    required: false

# comment for testing

runs:
  using: composite
  steps:
    - name: Set up Python version ${{ inputs.python-version }} (requirements.txt cache)
      if: ${{ inputs.requirements-txt }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: ${{ inputs.requirements-txt }}
    - name: Set up Python version ${{ inputs.python-version }} (no cache)
      if: ${{ !inputs.requirements-txt }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install build dependencies
      run: pip install --upgrade wheel
      shell: bash
    - name: Install dependencies
      if: ${{ inputs.requirements-txt }}
      run: pip install `for r in ${{ inputs.requirements-txt }}; do echo "-r $r"; done` ${{ inputs.pip-install-args }}
      shell: bash
    - name: Install packages
      if: ${{ inputs.packages }}
      run: pip install ${{ inputs.packages }} ${{ inputs.pip-install-args }}
      shell: bash
    - name: Run build command
      if: ${{ inputs.build-command }}
      run: ${{ inputs.build-command }}
      shell: bash
