name: repo-jobs

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: '21 13 * * 2'

name: repo-jobs

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  increment-version:
    if: ${{ github.event_name == 'push' || github.event_name == 'pull_request' }}
    name: Increment Version
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.run-increment-version.outputs.new-version }}
    steps:
      - name: Run the increment-version action
        id: run-increment-version
        uses: open-reading-frame/increment-version-action@main
        with:
          protect-tag: true
  check-version:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - name: Run the check-version action
        id: run-check-version
        uses: open-reading-frame/check-version-action@main
        with:
          include-paths: 'action.yml'
